### PR TITLE
Added do-while-loop

### LINKED ISSUE #72: [tutorial] JavaScript Exercise for Beginners
Hacktober Badge

**Description of the tutorial
 JavaScript exercises from books e.g. Eloquent JavaScript, JavaScript and JQuery), code challenges or code mastery sites (e.g. CodeWars, LeetCode, Interview Cake).
# content
* Challenges
* Code wars
* Examples 
* Docs
* tests
**Do you want to be assigned to work on this?**

- [X] YES
- [ ] NO

**Optional: Any additional info you want to add**
...
please assigned me for it  I hope that you will like my project file
Regards,

### LINKED ISSUE #73: [tutorial] do-while loop
**Description of the tutorial**
- What is a do...while loop
- How it is different from while loop
- Few basic questions on do...while loop

**Do you want to be assigned to work on this?**
(mark [x])
- [x] YES
- [ ] NO

**Optional: Any additional info you want to add**
- [x] I've read the CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by Parth-ops**
### 2. Description
- What is a do...while loop
- How it is different from while loop
- Few basic questions on do...while loop

### 3. Fill in checklist by marking [x]

- [x] I've read the CONTRIBUTING.md
- [x] I was assigned to this issue
- [x] My code is formatted using required linting
- [x] I've run my code locally and checked it works

### CODE REVIEW

**Comment by sabderemane** [comment]
The review of your PR will be done as soon as possible ✨

**Comment by Parth-ops** [comment]
@sabderemane thank you. Meanwhile is it ok if I open up another issue and start working on it?

**Comment by Parth-ops** [comment]
@sabderemane Hey, any updates on the PR review?

**Review by sabderemane — APPROVED** [review]
Sorry for the delay. Nice tutorial @Parth-ops, thank you for your contribution 💯

**Comment by sabderemane** [comment]
> Meanwhile is it ok if I open up another issue and start working on it?

You can open another issue and check the mark to be assigned on it for sure, we just don't want someone to have multiples issues assigned at the same time for a unique person if no PR is already open for the first issue assigned

**Comment by Parth-ops** [comment]
> Sorry for the delay. Nice tutorial @Parth-ops, thank you for your contribution 💯

It's ok and thank you very much :)

**Comment by Parth-ops** [comment]
> > Meanwhile is it ok if I open up another issue and start working on it?
> 
> You can open another issue and check the mark to be assigned on it for sure, we just don't want someone to have multiples issues assigned at the same time for a unique person if no PR is already open for the first issue assigned
Sure. I'll keep that in mind, thank you.

**Pull request merged**
